from pathlib import Path

BASE_DIR = Path(__file__).parent
DATA_DIR_NAME = "data"
CATEGORIES_FILENAME = "categories.csv"
PRODUCTS_FILENAME = "products.csv"
DATA_DIR = BASE_DIR / DATA_DIR_NAME
CATEGORIES_STORAGE_PATH = DATA_DIR / CATEGORIES_FILENAME
PRODUCTS_STORAGE_PATH = DATA_DIR / PRODUCTS_FILENAME


